"""empty message

Revision ID: 43ffcbed63f5
Revises: 3fc7c50a92be
Create Date: 2013-10-21 17:43:31.842183

"""

# revision identifiers, used by Alembic.
revision = '43ffcbed63f5'
down_revision = '3fc7c50a92be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
