"""empty message

Revision ID: af7c043638f
Revises: 43ffcbed63f5
Create Date: 2013-10-23 10:43:59.587804

"""

# revision identifiers, used by Alembic.
revision = 'af7c043638f'
down_revision = '43ffcbed63f5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow', sa.Column('created', sa.DateTime(), nullable=False))
    op.alter_column('follow', 'followee_id',
               existing_type=mysql.INTEGER(display_width=11),
               index=True,
               nullable=False)
    op.alter_column('follow', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               index=True,
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)
    op.alter_column('follow', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('follow', 'followee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('follow', 'created')
    ### end Alembic commands ###
