name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Debug
      run: |
        python -c "import sys; print(sys.version)"
        echo ${{ github.ref }}

    - name: Set up MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 3.4

    - name: Set up Redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: 3.2

    - name: Set up Minio
      run: |
        docker run -d -p 9000:9000 --name minio \
          -e "MINIO_ACCESS_KEY=minioadmin" \
          -e "MINIO_SECRET_KEY=minioadmin" \
          -v /tmp/data:/data \
          -v /tmp/config:/root/.minio \
          minio/minio server /data

        export AWS_ACCESS_KEY_ID=minioadmin
        export AWS_SECRET_ACCESS_KEY=minioadmin
        export AWS_EC2_METADATA_DISABLED=true

        aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://testbucket


    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Lint with Flake8
      run: |
        source venv/bin/activate
        make flake

    - name: Test
      env:
        STORE_S3_ENDPOINT: http://127.0.0.1:9000
        STORE_S3_BUCKET: testbucket
        STORE_S3_ACCESS_KEY: minioadmin
        STORE_S3_SECRET_KEY: minioadmin
      run: |
        source venv/bin/activate
        make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        fail_ci_if_error: false

